#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  leftSideEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightSideEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           rLBase,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lLift,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           fLBase,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mLBase,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           roller,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           fourBar,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           mRBase,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           fRBase,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           rLift,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          rRBase,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
